/*
#FULL ROSTER EXTRACT
SELECT * 
FROM A2C_ROSTER;

#FIND THE NECESSSARY INFORMATION OF ALL HOUSEHOLDS THAT ARE CURRENTLY ACTIVE
SELECT MEMBER_ID, PRIMARY_MEMBER, MEMBER_EMAIL, STATE, FAMILY_COUNT
FROM A2C_ROSTER
WHERE STATUS = 'ACTIVE';

#STATE LEVEL SUMMARY OF HOUSEHOLDS
SELECT STATE, SUM(FAMILY_COUNT) AS INDIVIDUALS
FROM A2C_ROSTER
WHERE STATUS = 'ACTIVE'
GROUP BY STATE
ORDER BY INDIVIDUALS DESC; 

#REGIONAL SUMMARY BY INDIVIDUALS
SELECT A2C_COMMUNITY, SUM(FAMILY_COUNT) AS INDIVIDUALS
FROM A2C_ROSTER
LEFT JOIN COMM_MAPPINGS
ON A2C_ROSTER.STATE = COMM_MAPPINGS.STATE
WHERE STATUS IN ('ACTIVE', 'STAFF')
GROUP BY A2C_COMMUNITY
ORDER BY INDIVIDUALS DESC; 

#FIND ACTIVE MEMBERS WITH HIGHER INCOME LEVELS WHO ARE ELIGIBLE FOR HOUSING IN THE WEST COMMUNITY
SELECT *
FROM A2C_ROSTER
LEFT JOIN COMM_MAPPINGS
ON A2C_ROSTER.STATE = COMM_MAPPINGS.STATE
LEFT JOIN MEMBER_DETAILS
ON A2C_ROSTER.MEMBER_ID = MEMBER_DETAILS.MEMBER_ID
WHERE STATUS = 'ACTIVE'
AND A2C_COMMUNITY = 'WEST'
AND INCOME_LVL IN ('50 to 100K', '>100K')
AND ROOM_TYPE = 'LARGE'
AND SPECIAL_NEEDS = 'N'
AND VETERAN = 'N'
AND FAMILY_COUNT >= 4; 

#AGGREGATES ACTIVE WEST COMMUNITY HOUSEHOLDS BY HOUSING_REASON
SELECT HOUSING_REASON, SUM(FAMILY_COUNT) AS INDIVIDUALS
FROM A2C_ROSTER
LEFT JOIN COMM_MAPPINGS
ON A2C_ROSTER.STATE = COMM_MAPPINGS.STATE
LEFT JOIN MEMBER_DETAILS
ON A2C_ROSTER.MEMBER_ID = MEMBER_DETAILS.MEMBER_ID
WHERE A2C_COMMUNITY = 'WEST'
AND STATUS = 'ACTIVE'
GROUP BY HOUSING_REASON
ORDER BY INDIVIDUALS DESC;

#LOCATE A SPECIFIC MEMBER IN THE ROSTER
SELECT *
FROM A2C_ROSTER
LEFT JOIN COMM_MAPPINGS
ON A2C_ROSTER.STATE = COMM_MAPPINGS.STATE
LEFT JOIN MEMBER_DETAILS
ON A2C_ROSTER.MEMBER_ID = MEMBER_DETAILS.MEMBER_ID
WHERE PRIMARY_MEMBER = 'Alisa Holmes'
AND MEMBER_EMAIL = 'Allmes@gmail.com'
AND HOUSING_REASON = 'Wildfire'
AND INCOME_LVL = '>100K'
AND SPECIAL_NEEDS = 'N'
AND VETERAN = 'N';

#LOCATE INFORMATION ON KANSAS FAMILIES DISPLACED DUE TO TORNADOES
SELECT HOUSING_REASON, COUNT(A2C_ROSTER.MEMBER_ID)
FROM A2C_ROSTER
LEFT JOIN MEMBER_DETAILS
ON A2C_ROSTER.MEMBER_ID = MEMBER_DETAILS.MEMBER_ID
WHERE STATE = 'KS'
GROUP BY HOUSING_REASON
ORDER BY COUNT(A2C_ROSTER.MEMBER_ID) DESC; */
#KANSAS REQUEST 2
SELECT PRIMARY_MEMBER, MEMBER_EMAIL, HOUSING_REASON, SPECIAL_NEEDS, VETERAN, STATE
FROM A2C_ROSTER
LEFT JOIN MEMBER_DETAILS
ON A2C_ROSTER.MEMBER_ID = MEMBER_DETAILS.MEMBER_ID
WHERE STATE = 'KS'
AND HOUSING_REASON = 'Tornado'
AND (SPECIAL_NEEDS = 'Y' OR VETERAN = 'Y');
